

exclude:
  #disable the boards which are not supported by the latest version of the library
- fqbn: arduino:renesas_uno:minima
  sketch:
      - examples/BLDC_Find_Polepairs/BLDC_Find_Polepairs.ino
      - examples/BLDC_HALL/BLDC_HALL.ino
      - examples/For_H_bridge/For_H_bridge.ino
      - examples/For_half_bridge/For_half_bridge.ino

- fqbn: arduino:renesas_uno:unor4wifi
  sketch:
      - examples/BLDC_Find_Polepairs/BLDC_Find_Polepairs.ino
      - examples/BLDC_HALL/BLDC_HALL.ino
      - examples/For_H_bridge/For_H_bridge.ino
      - examples/For_half_bridge/For_half_bridge.ino

- fqbn: arduino:samd:mkrzero
  sketch:
      - examples/BLDC_Find_Polepairs/BLDC_Find_Polepairs.ino
      - examples/BLDC_HALL/BLDC_HALL.ino
      - examples/For_H_bridge/For_H_bridge.ino
      - examples/For_half_bridge/For_half_bridge.ino

- fqbn: infineon:psoc6:cy8ckit_062s2_ai
  sketch:
      - examples/BLDC_Find_Polepairs/BLDC_Find_Polepairs.ino
      - examples/BLDC_HALL/BLDC_HALL.ino
      - examples/For_H_bridge/For_H_bridge.ino
      - examples/For_half_bridge/For_half_bridge.ino

- fqbn: infineon:xmc:kit_xmc_2go_xmc1100_v1
  sketch:
      - examples/BLDC_Find_Polepairs/BLDC_Find_Polepairs.ino
      - examples/BLDC_HALL/BLDC_HALL.ino
      - examples/For_H_bridge/For_H_bridge.ino
      - examples/For_half_bridge/For_half_bridge.ino

- fqbn: infineon:xmc:kit_xmc13_boot_001
  sketch:
      - examples/BLDC_Find_Polepairs/BLDC_Find_Polepairs.ino
      - examples/BLDC_HALL/BLDC_HALL.ino
      - examples/For_H_bridge/For_H_bridge.ino
      - examples/For_half_bridge/For_half_bridge.ino

- fqbn: infineon:xmc:kit_xmc1400_arduino
  sketch:
      - examples/BLDC_Find_Polepairs/BLDC_Find_Polepairs.ino
      - examples/BLDC_HALL/BLDC_HALL.ino
      - examples/For_H_bridge/For_H_bridge.ino
      - examples/For_half_bridge/For_half_bridge.ino

- fqbn: infineon:xmc:kit_xmc14_2go
  sketch:
      - examples/BLDC_Find_Polepairs/BLDC_Find_Polepairs.ino
      - examples/BLDC_HALL/BLDC_HALL.ino
      - examples/For_H_bridge/For_H_bridge.ino
      - examples/For_half_bridge/For_half_bridge.ino
